### ISSUE TITLE
Image size proportions

### ISSUE THREAD

**Issue by D4anielCB** [Astropulse/pixeldetector#1]
First of all thank you very much for your code, Im wondering what Im doing wrong, i want to keep the proportions, i used it on a image size of 1024x1024 and it resulted in a image of 128x205
Size detected and reduced from 1024x1024 to 128x205 in 1031 milliseconds
how can i keep the same proportions, like 128x128 or 205x205?
Thanks in advance

**Comment by Astropulse** [comment]
Hey! The code detects both horizontal and vertical patterns, so if you have a pixel art image that has been squished or stretched it can recover the original. Sometimes it gets confused and thats not the case, particularly if there is lots of empty space or non-pixel repeating patterns.

To make it only use the width or the height you could change [line 65](https://github.com/Astropulse/pixeldetector/blob/main/pixeldetector.py#L65) from `return kCentroid(image, round(image.width/np.median(hspacing)), round(image.height/np.median(vspacing)), 2), np.median(hspacing), np.median(vspacing)` to `return kCentroid(image, round(image.width/np.median(hspacing)), round(image.height/np.median(hspacing)), 2), np.median(hspacing), np.median(hspacing)`

This will only use the detected horizontal proportion.

**Comment by D4anielCB** [comment]
Thank you very much for the fast reply, im gonna try it
<3

**Comment by D4anielCB** [comment]
It worked like a charm, let me ask you something, is there a way to use your script to upscale the image, or do you know any that could do that?
Thanks again
