### ISSUE TITLE
怎么使用啊？在satable上面，有大佬知道吗？

### ISSUE THREAD

**Issue by zouanhao** [Astropulse/pixeldetector#2]

**Comment by tolusenum** [comment]
在PC上安装Python

打开cmd

“pip install Pillow"
"pip install scipy"

下载这个网页的 .zip, 
![example](https://github.com/Astropulse/pixeldetector/assets/138357378/f3414aa9-0dc2-45f9-880e-0cacbc4131cc)

提取 zip 文件

用cmd

"python pixeldetector.py -i input.png -o output.png --max 20"

input.png 是你的SDXL pixel lora 结果
