### ISSUE TITLE
Proportions changed

### ISSUE THREAD

**Issue by natsxd** [Astropulse/pixeldetector#3]
![image](https://github.com/Astropulse/pixeldetector/assets/126108873/a2e78629-9004-4e96-a9d8-2fdaf27b95cf)

Is it supposed to change proportions? I used a 1x1 image and it gave an output with different ratio, as can be seen in image

**Comment by Astropulse** [comment]
Yes, if it detects that the pixel ratios in the image are different. It calculates x/y ratios independently so it can handle images upscaled with odd ratios, or compression artifacts.
